# Generated by Django 3.0.6 on 2020-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_description', models.CharField(default='', max_length=400)),
                ('publish_date', models.DateField()),
                ('category', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('product_img', models.ImageField(default='', upload_to='shop/image')),
            ],
        ),
    ]
